#!/bin/bash

if ls --version 2>/dev/null | grep -q 'coreutils'; then
    alias ls='ls --color=auto'
else
    alias ls='ls -G'
fi

# Handy ls shortcuts
alias ll='ls -lh'
alias la='ls -A'
alias l='ls'

# Moving in dirs
alias ..='cd ..'
alias ...='cd ../..'

alias t='tmux -2 attach'
alias tn='tmux new-window'
alias ts='tmux split-window'

alias shtop='sudo htop'
alias v='vim'
alias sv='sudo vim'

#alias gac='git add -A && git commit'
#alias gacp='git add -A && git commit && git push'

# For vundle:
alias vim='env GIT_SSL_NO_VERIFY=true vim'

