#!/bin/bash

alias ls='ls --color=auto'

# Handy ls shortcuts
alias ll='ls -lh'
alias la='ls -A'
alias l='ls'

# Moving in dirs
alias ..='cd ..'
alias ...='cd ../..'

alias s='screen -U -D -R'
alias shtop='sudo htop'
alias svim='sudo vim'

alias gac='git add -A && git commit'
alias gacp='git add -A && git commit && git push'

# For vundle:
alias vim='env GIT_SSL_NO_VERIFY=true vim'

alias uio="ssh -Y josteibe@login.ifi.uio.no"
alias uiowin="rdesktop -d UiO -f windows.ifi.uio.no"
alias 1060="ssh josteibe@login.ifi.uio.no \"ssh inf1060@login.ifi\""
