#!/bin/bash

export PAGER="most"

export PATH="$PATH:$HOME/bin:$HOME/.dotfiles/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/repos/nim/bin"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$HOME/.rbenv/bin:$PATH"

export EDITOR="vim"
export RI="--format ansi"

[[ -s "$HOME/.env.local" ]] && . "$HOME/.env.local"
[[ -s "$HOME/.priv/dotfiles/envir" ]] && . "$HOME/.priv/dotfiles/envir"
