#!/bin/bash





ln -s ~/.dotfiles/zshrc ~/.zshrc
ln -s ~/.dotfiles/screenrc ~/.screenrc
ln -s ~/.dotfiles/dircolors ~/.dircolors
ln -s ~/.dotfiles/irbrc ~/.irbrc
ln -s ~/.dotfiles/gemrc ~/.gemrc
ln -s ~/.dotfiles/Xresources ~/.Xresources
ln -s ~/.dotfiles/Xresources ~/.Xdefaults



