#!/bin/bash




ln -s ~/.dotfiles/vimrc.local ~/.vimrc.local
ln -s ~/.dotfiles/vimrc.bundles.local ~/.vimrc.bundles.local

ln -s ~/.dotfiles/bashrc ~/.bashrc
ln -s ~/.dotfiles/screenrc ~/.screenrc
ln -s ~/.dotfiles/dircolors ~/.dircolors
ln -s ~/.dotfiles/irbrc ~/.irbrc
ln -s ~/.dotfiles/gemrc ~/.gemrc
ln -s ~/.dotfiles/Xresources ~/.Xresources
ln -s ~/.dotfiles/Xresources ~/.Xdefaults

ln -s ~/.dotfiles/lcirc ~/.lcirc



