#!/bin/bash





ln -s ~/.dotfiles/zshrc ~/.zshrc
ln -s ~/.dotfiles/screenrc ~/.screenrc
ln -s ~/.dotfiles/dircolors ~/.dircolors
ln -s ~/.dotfiles/irbrc ~/.irbrc
ln -s ~/.dotfiles/gemrc ~/.gemrc

ln -s ~/.dotfiles/lcirc ~/.lcirc




read -p "Install jbe's Vim configuration from Github? (y/N)" -n 1
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit
fi

cd ~
git clone http://github.com/jbe/.vim.git
ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc
cd ~/.vim
git submodule init
git submodule update
vim +BundleInstall +q

echo "ok"
