#!/bin/bash

if ls --version 2>/dev/null | grep -q 'coreutils'; then
    alias ls='ls --color=auto'
else
    alias ls='ls -G'
fi

alias ll='ls -lh'
alias la='ls -A'
alias l='ls'

alias ..='cd ..'
alias ...='cd ../..'

alias tn='tmux new-window'
alias ts='tmux split-window'

alias shtop='sudo htop'
alias v='vim'
alias g='gvim'
alias sv='sudo vim'

# Nim build scripts
alias cook='./cook'

# Git
alias ga='git add'
alias gc='git commit'
alias gs='git status'
#alias gac='git add -A && git commit'
#alias gacp='git add -A && git commit && git push'
alias gco='git checkout'
alias gb='git branch'
# For vundle:
alias vim='env GIT_SSL_NO_VERIFY=true vim'

alias ubuntu='lsb_release -cds'

# Ruby
alias be='bundle exec'
