#!/bin/bash

alias ll='ls -lh'
alias la='ls -A'
alias l='ls'

alias ..='cd ..'
alias ...='cd ../..'

alias dush='du -sh *'

alias tn='tmux new-window'
alias ts='tmux split-window'

alias shtop='sudo htop'
alias v='vim'
alias g='gvim'
alias sv='sudo vim'
alias vim='nvim'

alias serve='ruby -run -e httpd'

alias ubuntu='lsb_release -cds'

# Git
alias ga='git add'
alias gc='git commit'
alias gs='git status'
#alias gac='git add -A && git commit'
#alias gacp='git add -A && git commit && git push'
alias gco='git checkout'
alias gb='git branch'

# Ruby
alias be='bundle exec'
