#!/bin/bash

export PATH="$PATH:$HOME/bin"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$HOME/repos/Nim/bin"

export PATH="$PATH:$HOME/conf/global/bin"
