#!/bin/bash

export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/conf/global/bin"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$HOME/.cargo/bin:$PATH"
